env: flex
runtime: custom

skip_files:
  - ^node_modules/

readiness_check:
  path: /ok

resources:
  cpu: 1
  memory_gb: 1.6 # Default is 0.6
  disk_size_gb: 20 # Default is 10

automatic_scaling:
  min_num_instances: 3
  cpu_utilization:
    target_utilization: 0.8 # Default is 0.5
